### ISSUE TITLE
Gstreamer pipeline hangs with appsink element

### ISSUE THREAD

**Issue by waterflyfish** [InES-HPMM/linux-l4t#5]
Hello,
 when I use appsink to get data from a GStreamer pipeline,jetson tx1 will crash，and can not powered off,but if we only use sink like ximagesink,nvoverlaysink,udpsink...tx1 works well.It seems that tc358840 driver do not support Gstreamer's element appsink.  The pipeline I used si following
`gst-launch-1.0 v4l2src ! 'video/x-raw, format=UYVY, width=1280, height=720, framerate=(fraction)60/1' ! queue ! videoconvert ! appsink `
If i use ximagesink, nvoverlaysink, udpsink everything works fine .
Please advise if there is a workaround possible .
Regards

**Comment by tkammacher** [comment]
Discussed in https://devtalk.nvidia.com/default/topic/939179/jetson-tx1/4k-hdmi-capture-module-based-on-tc358840/5
There is a workaround for this issue:

#### kamm Posted 09/11/2017 08:48 AM

I have tested your pipeline and found that adding the following parameters to the appsink element allow the pipeline to be terminated with Ctrl+C by the user.
```
wait-on-eos=false
drop=true
max-buffers=60
```

A complete pipeline looks like this:
```
gst-launch-1.0 v4l2src device=/dev/video0 ! 'video/x-raw, width=1920, height=1080, framerate=60/1, format=UYVY' ! nvvidconv ! 'video/x-raw(memory:NVMM), width=1920, height=1080, format=I420, framerate=60/1' ! appsink wait-on-eos=false drop=true max-buffers=60 -e -vvv
```

From my understanding of GStreamer (and the appsink at [1]), it looks like appsink per default wants the streaming thread to block until pending buffers are emptied. This seems to cause issues with our implementation of the streaming kernel thread. So please try the method mentioned above, it is a workaround unless we might (hopefully) fix this issue in the drivers.

If performance is an issue, you can also use "io-mode=3" on the v4l2src, but must then replace nvvidconv with videoconvert and use the modified videoconvert [2] to avoid memory allocation issues.

[1]
https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-libs/html/gst-plugins-base-libs-appsink.html
[2]
https://github.com/InES-HPMM/linux-l4t/wiki/io-modes
